# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-04 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='google_id',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
